version: '3.4'

services:
  haishin:
    image: haishin
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - /root/haishin/backups:/app/public/backups
      - /root/haishin/streams:/app/public/streams
      - /root/haishin/uploads:/app/public/uploads