app = "personal-haishin-fe"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

swap_size_mb = 1024

[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]