app = "personal-haishin-be"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "haishin_staging_storage"
  destination = "/data"